repos:
  - repo: local
    hooks:
      # General checks
      - name: Prevent committing to main
        id: no-commit-to-branch
        language: system
        entry: no-commit-to-branch
        args: [--branch, main]
        pass_filenames: false
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
        language: system
        entry: end-of-file-fixer
        types: [text]
      - name: Remove trailing whitespace
        id: trailing-whitespace-fixer
        language: system
        entry: trailing-whitespace-fixer
        types: [text]
      - name: Check for files that would conflict on case-insensitive filesystem
        id: check-case-conflict
        language: system
        entry: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
        language: system
        entry: check-merge-conflict
        types: [text]
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
        language: system
        entry: check-executables-have-shebangs
        types: [executable]
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
        language: system
        entry: check-shebang-scripts-are-executable
        types: [text]
      - name: Don't allow adding large files
        id: check-added-large-files
        language: system
        entry: check-added-large-files

      # Markdown
      - name: Format markdown files
        id: markdown-format
        language: system
        entry: rumdl fmt
        types: [markdown]

      # YAML
      - name: Format YAML files
        id: yaml-format
        language: system
        entry: prettier --write
        types: [yaml]

      # TOML
      - name: Format TOML files
        id: toml-format
        language: system
        entry: taplo format
        types: [toml]

      # Nix
      - name: Format Nix files
        id: nix-format
        language: system
        entry: nixfmt
        types: [nix]
      - name: Lint Nix files
        id: deadnix
        language: system
        entry: deadnix
        types: [nix]

      # Just
      - name: Format Just files
        id: just-format
        language: system
        entry: just --unstable --fmt
        types: [text]
        files: ^Justfile$
        pass_filenames: false

      # Keep sorted
      - name: Keep sorted
        id: keep-sorted
        language: system
        entry: keep-sorted
        types: [text]

      # Typos
      - name: Check typos
        id: typos
        language: system
        entry: typos
        types: [text]
