id = "ssg-functional-programming"
title = "A static site generator is just a pure function"
description = "What I learnt by rewriting my website five times"
emoji = "ğŸŒ"
first_posted = 2023-09-26
last_updated = 2026-02-13
